# Generated by Django 2.2.1 on 2019-05-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilowatts', models.CharField(max_length=200)),
                ('time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
